name: Cloud-Zombie Analysis

on:
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'analyze'
        type: choice
        options:
          - analyze
          - optimize
          - report
      dry_run:
        description: 'Dry run (no changes)'
        required: true
        default: 'true'
        type: boolean
  push:
    paths:
      - 'targets/*.json'
      - 'targets/*.csv'

env:
  PYTHON_VERSION: '3.11'
  REPORTS_DIR: './reports'
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}

jobs:
  analyze:
    name: Analyze Cloud Resources
    runs-on: ubuntu-latest
    outputs:
      findings_count: ${{ steps.analyze.outputs.findings_count }}
      total_savings: ${{ steps.analyze.outputs.total_savings }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create reports directory
        run: mkdir -p ${{ env.REPORTS_DIR }}

      - name: Run FinOps Analysis
        id: analyze
        run: |
          python core/finops_analyzer.py 2>&1 | tee analysis_output.txt

          # Parse results (in real scenario, would analyze actual data files)
          echo "findings_count=0" >> $GITHUB_OUTPUT
          echo "total_savings=0" >> $GITHUB_OUTPUT

      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: optimization-reports
          path: ${{ env.REPORTS_DIR }}/
          retention-days: 30

      - name: Send Telegram notification
        if: always()
        run: |
          python -c "
          import os
          import json
          from core.telegram_bot import TelegramBot

          bot = TelegramBot()
          if bot.enabled:
              bot.send_message('🧟 Cloud-Zombie Analysis Complete\\n\\nCheck workflow results for details.')
          else:
              print('Telegram bot not configured')
          "

  optimize:
    name: Execute Optimizations
    runs-on: ubuntu-latest
    needs: analyze
    if: github.event.inputs.action == 'optimize' || github.event_name == 'schedule'
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install AWS CLI
        run: |
          which aws || (curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
          unzip awscliv2.zip && sudo ./aws/install)

      - name: Make scripts executable
        run: chmod +x scripts/*.sh

      - name: Run AWS Optimizations (Dry Run)
        env:
          DRY_RUN: ${{ github.event.inputs.dry_run || 'true' }}
        run: |
          echo "Running AWS optimization scripts..."
          # ./scripts/aws_optimizer.sh process reports/findings.json report

      - name: Upload optimization logs
        uses: actions/upload-artifact@v4
        with:
          name: optimization-logs
          path: logs/
          retention-days: 7

  report:
    name: Generate Report
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Generate Markdown Report
        run: |
          python -c "
          from core.finops_analyzer import FinOpsAnalyzer
          analyzer = FinOpsAnalyzer()
          report = analyzer.to_markdown()
          with open('reports/optimization_report.md', 'w') as f:
              f.write(report)
          "

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: reports/
          retention-days: 30

      - name: Create GitHub Issue
        if: github.event_name == 'schedule'
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: '🧟 Cloud-Zombie Optimization Report - ${{ github.event.repository.name }}'
          content-filepath: reports/optimization_report.md
          labels: finops, optimization, automated

  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: [analyze, report]
    if: always()

    steps:
      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          name: final-report
          path: reports/

      - name: Send Telegram Report
        run: |
          python -c "
          import os
          from core.telegram_bot import TelegramBot

          bot = TelegramBot()
          if bot.enabled:
              # Send summary
              bot.send_message('📊 Daily Cloud-Zombie Report Generated\\n\\nCheck GitHub Actions for details.')

              # Send file if available
              import os
              if os.path.exists('reports/optimization_report.md'):
                  bot.send_document('reports/optimization_report.md', 'Full Report')
          else:
              print('Telegram bot not configured')
          "
